# Generated by Django 4.1.7 on 2023-07-24 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promptbook', '0013_category_pinned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
